server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?serverTimezone=GMT%2B8
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
